name: dsproc Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Test list files - solution folder
      working-directory: ./UniDsproc
      run: ls
    
    #- name: Navigate to solution directory
    #  run: cd UniDsproc
    #  working-directory: $GITHUB_WORKSPACE

    #- name: Test list files - solution dir
    #  run: ls

    #- name: Create Build Directory
    #  run: mkdir _build
      
    - name: Restore Packages
      working-directory: ./UniDsproc
      run: nuget restore UniDsproc.sln

    - name: Build Solution
      working-directory: ./UniDsproc
      run: |
        msbuild.exe UniDsproc.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
        
    - name: GitHub Releases
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false
    #- name: GitHub Releases
    #  uses: fnkr/github-action-ghr@v1.3
    #  env:
    #      GHR_COMPRESS: zip
    #      GHR_PATH: ./_build
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
