name: dsproc Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Test list files - solution folder
      working-directory: ./UniDsproc
      run: ls
    
    #- name: Navigate to solution directory
    #  run: cd UniDsproc
    #  working-directory: $GITHUB_WORKSPACE

    #- name: Test list files - solution dir
    #  run: ls

    #- name: Create Build Directory
    #  run: mkdir _build
      
    - name: Restore Packages
      working-directory: ./UniDsproc
      run: nuget restore UniDsproc.sln

    - name: Build Solution
      working-directory: ./UniDsproc
      run: |
        msbuild.exe UniDsproc.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
        
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      env:
          GHR_COMPRESS: zip
          GHR_PATH: ./_build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
